language: php

php:
  - 7.2

addons:
  mariadb: 10.4

cache:
  directories:
    - node_modules
    - vendor
before_install:
  - mysql -e 'create database if not exists testing;'

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate -vvv
  - php artisan db:seed -vvv

script:
  - vendor/bin/phpunit
