language: php

php:
  - 7.2

addons:
  mariadb: 10.4

cache:
  directories:
    - node_modules
    - vendor
before_install:

before_script:
  - cp .env.travis .env
  - sudo mysql_upgrade
  - sudo service mysql restart
  - sudo mysqladmin create testing
  - sudo mysql -e "grant all privileges on testing.* to 'root'@'localhost'"
  - sudo mysql -e "select * from mysql.User;"
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate -vvv
  - php artisan db:seed -vvv

script:
  - vendor/bin/phpunit
